[theme]
primaryColor = "#1677A3"
backgroundColor = "#F4F7F8"
secondaryBackgroundColor = "#EDF2F4"
textColor = "#14212B"
font = "sans-serif"

[server]
headless = true

[browser]
gatherUsageStats = false

